### ISSUE TITLE
Bei leeren Favoriten Seite auf die Session Seite weiterleiten.

### ISSUE THREAD

**Issue by DerAlbertCom** [DerAlbertLive/conference-app#28]

**Comment by muescha** [comment]
Dieses neue Verhalten finde ich persönlich nicht so gut. 

Wenn ich auf Favoriten klicke möchte ich trotzdem auch nur eine leere Liste sehen. Ansonsten denkt man die App ist defekt.

**Comment by DerAlbertCom** [comment]
Ok, das verstehe ich wenn ich Favoriten explicit auswähle würde und dann auf Session gebounct würde. 

Ich bin davon ausgegangen das der Benutzer wenn die Site geöffnet wird das er als erstes seine gewählten Sessions sehen will. Wenn er aber noch keine Favoriten hat sieht er nur eine leere Seite und meint die App hat keine Infos und ist defekt. Daraus ergab sich der Redirect.

Welches Verhalten stellst Du Dir vor?

**Comment by muescha** [comment]
Die Reihenfolge der Tabs ändern:

1) Sessions
2) Speaker
3) Favoriten


Und merken welcher Tab zuletzt auf war wenn er erneut wiederkommt. 

Wenn er auf Favoriten war, dann gehts dann auch in die Favoriten. 

Optional: Bei leeren Favoriten eine Info anzeigen: zu Sessions wechseln entweder als Button oder oberhalb des Session Tab einen Pfeil darstellen so dass er selbst auf den Sessions Tab klickt.

**Comment by DerAlbertCom** [comment]
Was hälst Du davon das wenn man die App aufruft (und man somit keine Seite explicit gewählt hat) und dann auf der Favoriten Seite landet und nichts drin steht, dass man dann auf die Sessions weitergeleitet wird (wie jetzt auch). 

Aber wenn sie danach explizit anwählt per Navigation dass dann nicht auf Sessions weitergeleitet wird.

**Comment by muescha** [comment]
ja - auch ne gute Idee :)
